[PHP]
upload_max_filesize = 100M
post_max_size = 100M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

[Date]
date.timezone = Asia/Kolkata

[Session]
session.save_handler = redis
session.save_path = "tcp://redis:6379"
session.cookie_secure = 1
session.cookie_httponly = 1
session.cookie_samesite = Strict
session.gc_maxlifetime = 7200

[OpCache]
opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 2
opcache.fast_shutdown = 1

[Redis]
extension = redis